# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import adsb_pb2 as adsb__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adsb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlaneTrackingServiceStub(object):
    """ADS-B Plane Tracking Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllPlanes = channel.unary_unary(
                '/adsb.PlaneTrackingService/GetAllPlanes',
                request_serializer=adsb__pb2.GetAllPlanesRequest.SerializeToString,
                response_deserializer=adsb__pb2.GetAllPlanesResponse.FromString,
                _registered_method=True)
        self.StreamUpdates = channel.unary_stream(
                '/adsb.PlaneTrackingService/StreamUpdates',
                request_serializer=adsb__pb2.StreamUpdatesRequest.SerializeToString,
                response_deserializer=adsb__pb2.PlaneUpdate.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/adsb.PlaneTrackingService/GetStatus',
                request_serializer=adsb__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=adsb__pb2.GetStatusResponse.FromString,
                _registered_method=True)


class PlaneTrackingServiceServicer(object):
    """ADS-B Plane Tracking Service
    """

    def GetAllPlanes(self, request, context):
        """Get a snapshot of all currently tracked planes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUpdates(self, request, context):
        """Stream continuous updates (additions, updates, removals)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get service status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaneTrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllPlanes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPlanes,
                    request_deserializer=adsb__pb2.GetAllPlanesRequest.FromString,
                    response_serializer=adsb__pb2.GetAllPlanesResponse.SerializeToString,
            ),
            'StreamUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUpdates,
                    request_deserializer=adsb__pb2.StreamUpdatesRequest.FromString,
                    response_serializer=adsb__pb2.PlaneUpdate.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=adsb__pb2.GetStatusRequest.FromString,
                    response_serializer=adsb__pb2.GetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adsb.PlaneTrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adsb.PlaneTrackingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaneTrackingService(object):
    """ADS-B Plane Tracking Service
    """

    @staticmethod
    def GetAllPlanes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adsb.PlaneTrackingService/GetAllPlanes',
            adsb__pb2.GetAllPlanesRequest.SerializeToString,
            adsb__pb2.GetAllPlanesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/adsb.PlaneTrackingService/StreamUpdates',
            adsb__pb2.StreamUpdatesRequest.SerializeToString,
            adsb__pb2.PlaneUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adsb.PlaneTrackingService/GetStatus',
            adsb__pb2.GetStatusRequest.SerializeToString,
            adsb__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
